// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoTIJS5z_Ivv-c-Bo6MxoSLHthBbVR4WU',
    appId: '1:64370557085:web:f1f8ed67583407f9621474',
    messagingSenderId: '64370557085',
    projectId: 'wakeuphoneys2',
    authDomain: 'wakeuphoneys2.firebaseapp.com',
    storageBucket: 'wakeuphoneys2.appspot.com',
    measurementId: 'G-DQNM2ZGSMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjlrCyHdhq0cxbGMGJ6zPSYPwidmHK-YI',
    appId: '1:64370557085:android:bf0d4de4241e0d28621474',
    messagingSenderId: '64370557085',
    projectId: 'wakeuphoneys2',
    storageBucket: 'wakeuphoneys2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhtqTd7BqzIs-62C9o0u-aRQWz0U1hswc',
    appId: '1:64370557085:ios:aeea4d4b85727c97621474',
    messagingSenderId: '64370557085',
    projectId: 'wakeuphoneys2',
    storageBucket: 'wakeuphoneys2.appspot.com',
    androidClientId: '64370557085-imdd5566vj4fcu3ok811ip7rhma3csit.apps.googleusercontent.com',
    iosClientId: '64370557085-pnl2s9291k0dp8ij8ugl25c92psedsdi.apps.googleusercontent.com',
    iosBundleId: 'com.wakeuptaco.wakeuphoney',
  );
}
